version: 2

models:
  - name: stg_populacao
    description: |
      9606 - População residente, por cor ou raça, segundo o sexo e a idade
    tags: ["staging", "brasil", "censo"]
    columns:
      - name: id_municipio
        description: Identificador único de município.
        tests:
          - not_null
      - name: grupo_idade
        description: Intervalo de idade do grupo.
        tests:
          - not_null
      - name: sexo
        description: Determina o sexo daquele grupo.
        tests:
          - not_null
          - accepted_values:
                values: [ 'Homens', 'Mulheres' ]
      - name: cor_raca
        description: Determina a raça daquele grupo.
        tests:
          - not_null
          - accepted_values:
                values: [ 'Amarela', 'Branca', 'Indígena', 'Parda', 'Preta' ]
      - name: populacao
        description: População determinada para aquele grupo na região.
        tests:
          - not_null
  - name: stg_municipio
    description: |
      Municipios brasileiros e seus respectivos estados
    tags: [ "staging", "brasil", "estados", "municipios" ]
    columns:
      - name: cd_municipio
        description: Código do município.
        tests:
          - not_null
      - name: nm_municipio
        description: Nome do município.
        tests:
          - not_null
      - name: cod_municipio_completo
        description: Código IBGE do município completo.
        tests:
          - not_null
          - unique
      - name: uf
        description: Código do estado.
        tests:
          - not_null
      - name: nome_uf
        description: Nome do estado.
        tests:
          - not_null
